fix: cleaner sign share request implementation
xoloki/wsts pull request #114
Opened 2024-12-24 19:28 UTC by djordon

## Description

This builds off of https://github.com/Trust-Machines/wsts/pull/107, which addressed https://github.com/Trust-Machines/wsts/issues/108.

## Changes 

* Fixes an off-by-one error in the current implementation.
* Simplifies the implementation of `sign_share_request` slightly.

## Testing

I still need to test all of the conditions checked for in the `sign_share_request` function.

2025-01-08 13:40 UTC, xoloki requested changes
Looks good, modulo a number of questions and suggestions.  The naming of `is_valid_request` is the only critical one.

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/coordinator/mod.rs
> +        assert_eq!(outbound_messages.len(), 1);
This `assert!` is a duplicate of the one on line `1112`.

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/coordinator/mod.rs
> +        let result = feedback_messages_with_errors(&mut coordinators, &mut signers, &messages);
Is the point here to verify that the original `SignatureShareRequest` succeeds without mutation?

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/coordinator/mod.rs
> +            request
So rather than testing an excessively large number of nonce responses, as in the original bug, you're simply testing a single duplicate?

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/coordinator/mod.rs
> +            request
Should we also try an out-of-range `signer_id`?

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/signer/mod.rs
> +        let is_valid_request = sign_request.nonce_responses.len() != signer_id_set.len()
You appear to be checking for an invalid request, not a valid request, so shouldn't you rename this variable?

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/signer/mod.rs
> +        debug!(%self.signer_id, "received a valid SignatureShareRequest");
Should we include the full set of `signer_ids` as in the log line that got refactored out?

2025-01-08 13:40 UTC, xoloki commented on src/state_machine/signer/mod.rs
> +        debug!(%self.signer_id, "received a valid SignatureShareRequest");
Also, shouldn't we log this as `signer_id = %self.signer_id` ?

2025-01-08 13:54 UTC, djordon commented on src/state_machine/signer/mod.rs
> +        let is_valid_request = sign_request.nonce_responses.len() != signer_id_set.len()
Oh yeah, or change `!=` to `==`.

2025-01-08 13:56 UTC, djordon commented on src/state_machine/signer/mod.rs
> +        debug!(%self.signer_id, "received a valid SignatureShareRequest");
> Should we include the full set of `signer_ids` as in the log line that got refactored out?

Well that I'm not so sure of. That could be a large log line.

> Also, shouldn't we log this as `signer_id = %self.signer_id` ?

Yup, will update.

2025-01-08 13:57 UTC, djordon commented on src/state_machine/coordinator/mod.rs
> +        assert_eq!(outbound_messages.len(), 1);
Oh right, will remove.

2025-01-08 13:58 UTC, djordon commented on src/state_machine/coordinator/mod.rs
> +        let result = feedback_messages_with_errors(&mut coordinators, &mut signers, &messages);
Yup, show that things work as normal when things aren't modified, just as a sanity check.

2025-01-08 14:09 UTC, djordon commented on src/state_machine/coordinator/mod.rs
> +            request
> So rather than testing an excessively large number of nonce responses, as in the original bug, you're simply testing a single duplicate?

Yup. Testing for any duplicates implicitly covers too large a number of nonce responses. The previous testing approach could have allowed for a single duplicate, even though the code was fine.

This test isn't perfect either.

> Should we also try an out-of-range `signer_id`?

Yeah, that's one of the tests that I wanted to add. We need to test for all of the conditions checked for in the code.

2025-01-14 15:21 UTC, xoloki commented on src/state_machine/coordinator/mod.rs
> +            request
Ok, I added tests cases with no `NonceResponse` and with and out-of-range `signer_id`.

2025-01-14 15:22 UTC, xoloki approved these changes

2025-01-14 16:05 UTC, djordon reviewed
Looks good!

2025-01-14 16:06 UTC, merged